# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_annonymous', models.BooleanField(default=1)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
